### ISSUE TITLE
[User Registration] Make email required on backend

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/backend#111]
## Context
We need to make sure the email field is required when a new user is registered via the /auth/users API endpoint. 

## Acceptance Criteria
[ ] Change the line in the model to make sure email is required
[ ] Make migrations file and run migrations
[ ] Add models test
[ ] Make sure tests pass

## Ticket sizing
1 (small)

**Comment by BethanyG** [comment]
@lpatmo  This is not an API change  and since we are using a **custom model**, it is an _**addition**_.

Add `email`  in users_user  as a required (non-blank) field.

Since we are using a custom user model, this change will need to be made in the `model.py` file of the **`users`** app.

*  [**Custom User Models (Django Docs)**](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project)
*  [**Referencing the Custom User Model (Django Docs)**](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#referencing-the-user-model)
*  [**Related SO Post on Requiring Email for Custom User Model**](https://stackoverflow.com/questions/49134831/django-make-user-email-required)

**Comment by lpatmo** [comment]
Gah I was going to give this to @bkbuilt or someone else who expressed interest since it's a good beginner issue, but started playing around to test it out in a new branch and realized I might as well create a PR for it.

PR: https://github.com/chris48s/backend/pull/1/files

Note that it is based off of https://github.com/codebuddies/backend/pull/109. 

I documented my implementation steps in https://github.com/chris48s/backend/pull/1, so if something drastic changes in https://github.com/codebuddies/backend/pull/109 the implementation steps should be easily re-created.

**Comment by lpatmo** [comment]
(Or... if #109 gets merged in first, I'll just re-submit the PR to point towards `master` instead of towards Chris' branch)

**Comment by BethanyG** [comment]
@lpatmo I hate to do this to you, but for clarities sake, I really think this should be  a separate PR...just so we keep related PRs with their milestones??

**Comment by lpatmo** [comment]
No problem, I meant to do this as a separate PR, but realized this was dependent on the other PR being merged in 😅. Happy to resubmit the PR to `master` after that other PR is resolved!

**Comment by BethanyG** [comment]
🤔   ...yeah.  We need to get our arses in gear around testing....aaaaand you'll need to add a model test for your change 😄 .

**Comment by lpatmo** [comment]
Haha, cool! I missed that in my acceptance criteria 😅

**Comment by lpatmo** [comment]
I _think_ we can recreate what I did in https://github.com/chris48s/backend/pull/1/files, plus add some tests to the model. Need to research where that will live, though 🤔

**Comment by bengineerdavis** [comment]
> I _think_ we can recreate what I did in https://github.com/chris48s/backend/pull/1/files, plus add some tests to the model. Need to research where that will live, though thinking

Do you mind adding this and other things you find for our 'prep' in our [public docs](https://docs.google.com/document/d/e/2PACX-1vTpA-BcbCu0uEkqVfBM5L7exoIF_BC4GW1VtGDLAxKcYb9Q9FeYKtdB8CxsHxxmJ2DR1G255QW37zK3/pub)?

**Comment by BethanyG** [comment]
@lpatmo @bengineerdavis @tgrrr -- apologies for not replying to this earlier. This change is needed for #113, #110, #113 which I am currently working on.  I don't think that what I am doing will interfere with this -- or vice-versa, but there may be merge conflicts if we're both checking in code in the next few days.

**Comment by lpatmo** [comment]
Thanks for the heads up! We probably won't have a PR up sooner than next Tuesday (when https://codebuddies.org/hangout/nAadjwkpEsF9gsTGM is scheduled), fwiw. 

In the meantime, added this as reading to the google doc: https://www.obeythetestinggoat.com/book/chapter_database_layer_validation.html

**Comment by BethanyG** [comment]
In investigating further the changes needed for email validation in registration, I've made a few discoveries that now (I believe) cancel out this change entirely.  

Firstly, I didn't realize that `cookiecutter-django` (_which we used to generate this project_) **_pre-installed_** [django-allauth](https://django-allauth.readthedocs.io/en/latest/installation.html) in addition to implementing a custom user model.  See [Cookiecutter Settings Page](https://cookiecutter-django.readthedocs.io/en/latest/settings.html) for a little info on that.  

Secondly, in looking at the DB and the [allauth configuration docs](https://django-allauth.readthedocs.io/en/latest/configuration.html) and the [allauth custom user models docs](https://django-allauth.readthedocs.io/en/latest/advanced.html#custom-user-models) around configuration and custom user models, I noticed the following:

![image](https://user-images.githubusercontent.com/5923094/92417547-9ab02b80-f117-11ea-9f39-0b237943b898.png)

and 

![image](https://user-images.githubusercontent.com/5923094/92417920-b3b9dc00-f119-11ea-85b1-76c516819587.png)


...which means that `allauth` - either configured for social OR configured for email uses a special app and set of tables under `accounts` to store emails for users for authentication -- **not** the users_user table.  The flag `ACCOUNT_EMAIL_REQUIRED=True` is for the **`account`** app and the **`account_email`** table -- **NOT** the `email` field in the `users` app, or the `users_user` table!

**Why is this important?**  Having `django-allauth` pre-installed means we don't have to create the user registration/validation/confirmation flow from scratch - much of it is handled by the allauth app.  BUT.  That also means that the email requirement needs to be applied through `django-allauth` -- not through the `users` model.

Apologies that I didn't see this before -- would probably have saved a lot of reading and work.

**Comment by BethanyG** [comment]
Recommend that if you do go ahead and make this change that it not be merged (nor should the registrations changes I am making be merged) until we decide which direction we are going to go with registration.

**Comment by lpatmo** [comment]
D'oh and LOL SO GLAD YOU NOTICED THIS!! 

I'll continue the discussion re: authentication in https://github.com/codebuddies/backend/discussions/178 :) 

(In the meantime, I'll close this issue since it's not needed anymore)

**Comment by tgrrr** [comment]
Copied for reference here:

@BethanyG wrote on https://github.com/codebuddies/backend/issues/111:
> We closed #111, because the authentication scheme we are using doesn't trigger off an email on the custom user model. See comments there and on discussion number 
https://github.com/codebuddies/backend/issues/178.

**Comment by tgrrr** [comment]
I also found this branch from @lpatmo working on this issue, dropping the link here for reference: https://github.com/codebuddies/backend/commit/ff5c10bee2a4366ad3dbf5edfd4e2e2f46b9dd34

**Comment by BethanyG** [comment]
@tgrrr - this issue has been closed by @lpatmo and is unlikely to be reopened.  Please see the comments above.  Unless we decide we are re-creating email validation and user registration flows from scratch (very unlikely), we will have no need for the change.  @lpatmo work was never merged  and is not present in `main`.

**Comment by bengineerdavis** [comment]
That makes sense that we don't want to reinvent the wheel if we don't have
to. I got the impression that the settings.py change for the environmental
variable you found hadn't been changed, or was that already pre-configured?
