### ISSUE TITLE
[Testing] [WIP] Use Factory-Boy to Create  Seed Data for Dev and Staging DBs

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#115]
This needs more detail, but I am logging this here so I don't forget it.  Will update with detail shortly.

**Comment by chris48s** [comment]
Now #116 is merged I'm happy to pick this one up. I think its pretty straightforward:

:factory:   Write a management command to build some test data using factories
:x:  Delete the fixture files
:books:  Update the docs with how to init DB with test data

Are you happy for me to just run with it, or do you want to pair on this one too?

**Comment by BethanyG** [comment]
Hey!  Now I have emoji bullet envy.  😄 

Every time I think of this issue, I get hung up on introducing some sort of "meaning" to the data...like I want to make it "pretty" for display, or have a set of "realistic" resources with related tags...or resources that would have different groupings for search....and that is probably not a good thing.  I think my brain is just stuck on the fixtures that I use out of habit.  🙄   

So YES YES - more than happy to have you take this up.  Have fun playing with it.....and since you are doing it programmatically, it would be great to make a default batch of say 50+ or so ...or maybe even a configurable batch?

We may also want to do something like scrape tech related urls to select from..or not.  How about I back away slowly and let you get to work?  Yup, that's what I should do.  😉
