### ISSUE TITLE
[API] Make the GET /resources endpoint public

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/backend#128]
## Context
Right now, on the front-end, we need to pass in a token (i.e. the user needs to be logged in) before they can see a list of resource. 

```
 axios
      .get('/api/v1/resources', {
        headers: {
          Authorization: `Bearer ${authContext.authTokens.token}`,
        },
      })
```
This should be true for when users are creating a resource, but the list of resources on https://cb-react-concept.netlify.com/resources should be available to the public.

## Acceptance Criteria
[ ] Make GET /resources not protected by authorization
[ ] Change setup for tests to make sure we're not authed for the GET requests, but are authed for POST, PATCH, and search.
[ ] Add test to make sure GET /api/v1/resources/{{guid}}/ and GET /api/v1/resources/ requests and search work without a token
[ ] Add/alter tests for GET GET /api/v1/resources/{{guid}}/ and GET /api/v1/resources/ requests and search to ensure that they also work with a token
[ ] Add tests to make sure PATCH and POST fail without a token
[ ] Add test to make sure DEL fails without a token

**Comment by chris48s** [comment]
If you wanted to use this as an issue to walk someone through their first contribution, this should be close to a one-line change to the API code:

https://www.django-rest-framework.org/api-guide/permissions/#isauthenticatedorreadonly

```py
from rest_framework import permissions

class ResourceView():
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    #...
```

- Set up a dev environment
- Make that change
- Write a test
- Submit a PR

probably fits nicely into a 1 hour hangout.

**Comment by lpatmo** [comment]
> probably fits nicely into a 1 hour hangout.
 
That's a GREAT idea!! I will raise it up in #codebuddies-meta. 

_I_ could actually use some guidance on how to write a test for this, heh. We're primarily testing that the GET /resources endpoint works without passing in an auth token, right?

**Comment by lpatmo** [comment]
Confirmed that `IsAuthenticatedOrReadOnly` works! 🎆Yay. 

Updated the acceptance criteria with some ideas for tests (h/t @BethanyG for suggesting in #codebuddies-meta):

[ ] Change setup for tests to make sure we're not authed for the GET requests
[ ] Write test to make sure GET `/api/v1/resources/{{guid}}/` and GET `/api/v1/resources/` requests work without a token
[ ] Write test to make sure PATCH and POST requires a token

**Comment by chris48s** [comment]
> I could actually use some guidance on how to write a test for this

Reading your next post plus slack, it looks like you've already figured it out tbh :)

**Comment by lpatmo** [comment]
🤞🤞:)

**Comment by lpatmo** [comment]
PR: https://github.com/codebuddies/backend/pull/134
