### ISSUE TITLE
[Tooling] Run linting/coding standards checks

### ISSUE THREAD

**Issue by chris48s** [codebuddies/backend#132]
My go-to combo is:

:8ball:  [flake8](https://pypi.org/project/flake8/)
:black_circle:  [black](https://github.com/psf/black)
:spiral_notepad:   [isort](https://github.com/timothycrosley/isort)

[pylint](https://www.pylint.org/) is also a popular choice

**Comment by BethanyG** [comment]
Closing for the moment.  Not that this isn't excellent -- just that we might want to add this to documentation, or otherwise set up actions, reviews, or some sort of templates yet TBD.
