### ISSUE TITLE
[Tooling] Staging API Deployment Strategy

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/backend#139]
## Context
We need a staging API that https://cbv3.netlify.app/ (our frontend staging app) can consume. 

Figuring this out right now is also good practice for when we _actually_ deploy to production. :) 

## Acceptance Criteria
[ ] Create a staging branch
[ ] Create a new `Django` workflow in Github Actions
https://github.com/codebuddies/backend/actions/new
[ ] Create a DigitalOcean droplet
[ ] Create a postgres DB on DigitalOcean
[ ] Figure out how to deploy from that `staging` branch into my new workflow in Github Actions (?) - probably related to the contents of the docker-compose-staging.yml file below. 
[x] brew install doctl
[ ] Create a docker-compose-staging.yaml file
[ ] Add/remove environment variables in GitHub secrets at https://github.com/codebuddies/backend/settings/secrets
[ ] Basically, follow the amazing documentation Bill wrote up in https://github.com/codebuddies/backend/wiki/Production-Deployment

## Other notes/screenshots
See: [cbv3 notes doc](https://docs.google.com/document/d/1YuVO-v0n73ogoFIwpwJgI1Bkso8sP2mg5zqbX9FB3lU/edit#)
Also see: https://github.com/codebuddies/backend/issues/65

**Comment by lpatmo** [comment]
(Ideally planning to look at this over the next few days in my free time, document in the notes doc, and will ask if I need help)

**Comment by BethanyG** [comment]
@lpatmo   Is this still relevant?  Can we close?

**Comment by lpatmo** [comment]
Er, actually this is still on my plate to do!

**Comment by BethanyG** [comment]
@lpatmo  - are you done with this issue, or should we keep it open?

**Comment by lpatmo** [comment]
Sorry this issue is taking forever; been a stressful couple of weeks. :( Made some progress last month, but current status is: https://github.com/codebuddies/backend/discussions/177#discussioncomment-84002. I'll keep that thread updated!
