### ISSUE TITLE
[Tooling] Add GET endpoint for search to POSTMAN

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/backend#149]
### Acceptance Criteria
[ ] Add /api/v1/resources/?search=KEYWORD as a GET endpoint to Postman
[ ] Final Postman collection should look something like:
![image](https://user-images.githubusercontent.com/4512699/88751818-46279280-d10d-11ea-8ed0-5de80ff21188.png)

### Ticket estimate
2 (small)

**Comment by BethanyG** [comment]
Please note that we currently only have a [**very** basic](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) search filter enabled in DRF. 

**Current search fields are:**  'guid', 'media_type', 'title', & 'description'.  

`author`, `user`, `tags`,  `url` (main & referring), `date_published`,  `date_created`, `date_modified`, and `paid` **are not searched**.

**Comment by lpatmo** [comment]
I believe @watchtheblur started working on this in a new branch, so he'll make a PR for it soon.

**Comment by watchtheblur** [comment]
The collection currently committed doesn't have the "PATCH a resource" in the screenshot above.  Is that ok?

**Comment by lpatmo** [comment]
I think that's ok! I just realized I created a `PATCH` endpoint for myself, and we should get that into Postman too, but another issue/PR for that is fine.
