### ISSUE TITLE
[Tooling] Consider Upgrading to Django 3.0 and DRF 3.11

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#182]
With Django 3.11 in mainstream release, and [LTS for Django 2.2](https://www.djangoproject.com/download/#supported-versions) series due to end in 2022, we might want to research/consider upgrading as far as we can while we are still pre-production deployment for the site.  Better to take the compatibility hits now than try to do so after we have users and data to support.

**A quick rundown of Libraries and compatibilities:**

| Library                  	| Current Version 	| Version of Django Supported    	| Notes                                  	| URL of Project                                              	|
|--------------------------	|-----------------	|--------------------------------	|----------------------------------------	|-------------------------------------------------------------	|
| django                   	| 2.2.4           	| Up to 3.11                     	|                                        	| https://www.djangoproject.com/                              	|
| django-allauth           	| 0.39.1          	| 2.0+                           	|                                        	| https://github.com/pennersr/django-allauth                  	|
| django-celery-beat       	| 1.5.0           	| Up to 2.11 (later unknown)     	| Not currently used, might be in future 	| https://github.com/celery/django-celery-beat                	|
| django-cors-headers      	| 3.0.2           	| Up to 3.11                     	|                                        	| https://github.com/adamchainz/django-cors-headers           	|
| django-crispy-forms      	| 1.7.2           	| Up to 3.11                     	|                                        	| https://github.com/django-crispy-forms/django-crispy-forms  	|
| django-environ           	| 0.4.5           	| Up to 3.0                      	|                                        	| https://github.com/joke2k/django-environ                    	|
| django-filter            	| 2.2.0           	| Up to 3.0                      	|                                        	| https://github.com/carltongibson/django-filter              	|
| django-model-utils       	| 3.2.0           	| 3+                             	|                                        	| https://github.com/jazzband/django-model-utils              	|
| django-redis             	| 4.10.0          	| 2.2+                           	| Not currently used, might be in future 	| https://github.com/niwinz/django-redis                      	|
| django-taggit            	| 1.2.0           	| 1.11+                          	|                                        	| https://github.com/jazzband/django-taggit                   	|
| djangorestframework      	| 3.10.2          	| Up to 3.0                      	|                                        	| https://github.com/encode/django-rest-framework             	|
| coreapi                  	| 2.3.3           	| NA (depends on python version) 	|                                        	| https://github.com/core-api/python-client                   	|
| django_taggit_serializer 	| 0.1.7           	| Unknown                        	| In use, could break with new version   	| https://github.com/glemmaPaul/django-taggit-serializer      	|
| drf-jwt                  	| 1.13.4          	| 1.11+                          	|                                        	| https://github.com/Styria-Digital/django-rest-framework-jwt 	|
| django-rest-auth         	| 0.9.5           	| Unknown                        	| In use, could break with new version   	| https://github.com/Tivix/django-rest-auth                   	|
| django-rest-authtoken    	| 2.1.3           	| Unknown                        	| Not currently in use                   	| https://pypi.org/project/django-rest-authtoken/             	|
|                          	|                 	|                                	|                                        	|                                                             	|

**Comment by lpatmo** [comment]
👏 👏 👏  

So in terms of testing this out, I imagine the process could be:
- create a new branch
- upgrade Django to 3.11
- test out which dependencies break

**Comment by BethanyG** [comment]
Yup!  Agree.  But I think I want to figure out the Registration flow **before** we do that - it is feeling really messy and brittle, and I don't want to add to the mess of things that might break.  Thoughts?

**Comment by lpatmo** [comment]
Yeah, definitely. Let's figure out registration first!

**Comment by BethanyG** [comment]
_Not stale.  Just baking...._

**Comment by BethanyG** [comment]
Still open.

**Comment by BethanyG** [comment]
Still open. Just sleeping.
