### ISSUE TITLE
Add DigitalOcean to the list of sponsors in the README

### ISSUE THREAD

**Issue by billglover** [codebuddies/backend#196]
**Current:**
It looks like DigitalOcean has been left off the list of sponsors in the README. I believe they still sponsor hosting.

**Expected:**
DigitalOcean logo (and link) is listed on the README under the Sponsorship section.

**Comment by lpatmo** [comment]
Thank you, that's a good catch! 😅  I included this in https://github.com/codebuddies/backend/pull/195 since I happened to have a PR open to update the README right now.

**Comment by lpatmo** [comment]
Closed by https://github.com/codebuddies/backend/pull/195
