### ISSUE TITLE
[API] Set up "Dynamic" Search for `api/v1/resources/`

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#22]
Currently,  `api/v1/resources/` uses `filters.SearchFilter` as its filter_backend.  This particular filter does a search on all fields for the requested parameters, which is not granular enough for our search needs.

As in this article:  https://medium.com/better-programming/how-to-make-search-fields-dynamic-in-django-rest-framework-72922bfa1543? we need to make this api endpoint more dynamically searchable by implementing a custom filter_backend.

**Comment by BethanyG** [comment]
There is an additional twist for this now that we are using a generic relation  for Tags through taggit.

**Comment by BethanyG** [comment]
Going to try and take a shot at this at some point soon, but would welcome some collaborators.

**Comment by billglover** [comment]
Am I right in understanding that the aim of this is to allow the user to specify which fields they'd like their search query matched against as part of the search request and that without this the default is to search all fields?

**Comment by BethanyG** [comment]
That is correct.   The current implementation is a "default" implementation of the [**DRF Filter Backend**](https://www.django-rest-framework.org/api-guide/filtering/#filtering-against-query-parameters), which

**Comment by BethanyG** [comment]
**Correction**.  We are using the [**DRF Filter Backend**](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) - but functionally, it more or less has the same effect.  Yes - we can control which fields the search runs against, but it is not a very intelligent search - and we cannot currently include tags as part of the search fields.

**Comment by BethanyG** [comment]
Putting this on hold for a bit while we thin through hangouts and tagging and weather or not we will be using something like haystack or something else.
