### ISSUE TITLE
[File restructuring]Move project files to repository root

### ISSUE THREAD

**Issue by brylie** [codebuddies/backend#30]
Several files were added to the project, probably by Cookiecutter Django, in a sub-directory, such as the LICENSE and .gitignore files. It is conventional to keep these files in the repository root.

It might be simpler to move all of the project files, keeping the sub-structure, to the project root.

## Task
- [x] Move all project files under the `cbv3_django_prototype` directory to the repository root

Related task: #26

**Comment by billglover** [comment]
Hold until #43 is complete.

Could be completed with #31 and #50.

**Comment by billglover** [comment]
@lpatmo you are assigned to this one. I've just removed the `hold` tag.

**Comment by billglover** [comment]
This looks like it was addressed by #99.
