### ISSUE TITLE
[File restructuring]Django apps should be defined in project root

### ISSUE THREAD

**Issue by brylie** [codebuddies/backend#31]
Currently, this project is defining some Django apps in the `cbv3_django_prototype/cbv3_django_prototype` sub-directory. The `project_name/project__name` sub-directory is conventionally used for project-wide configuration. The Cookiecutter Django project may recommend a different file structure, but it is not apparent from a quick search of the documentation. However, running `python manage.py startapp app_name` in the project root creates the app in the project root, which is a fairly conventional project structure. This is a small mistake that is easy to fix.

## Task
- [ ] Consider reorganizing the project, so that apps are created in the project root (rather than in the nested directory)
- [ ] Move all existing apps (namely, `resources` and `users`) to the project root

## Reference
- Django docs - [Projects and applications](https://docs.djangoproject.com/en/3.0/ref/applications/#projects-and-applications)

**Comment by billglover** [comment]
Hold until #43 is complete.

Could be completed with #30 and #50.

**Comment by billglover** [comment]
I'm not convinced we want to implement this. The project root contains items unrelated to Django such as the `nginx` configuration, the `postman` collection, and the `docker-compose.yaml`.

**Comment by brylie** [comment]
For clarification, the *project* root is where `manage.py` is located (currently `backend/cbv3_django_prototype`). The *repository* root is where the `docker-compose.yaml` is located (currently `backend/`).

It is [conventional for Django apps to be defined in the *project* root](https://docs.djangoproject.com/en/3.0/ref/applications/#projects-and-applications). Following Django conventions makes our codebase easier to approach by new users, particularly when they are familiar with Django conventions.

**Comment by billglover** [comment]
Awesome, understood. This makes a lot of sense.

**Comment by billglover** [comment]
This looks like it was closed with c6dd158.
