### ISSUE TITLE
[Testing]Rewrite Application Tests to Use Factory-Boy

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#48]
The current Application tests load Fixture data for JWT and Resource testing.  These should now be re-written to use Factory Boy (or Model Mommy), so that they are not dependent on static or moldy  data.

**Comment by BethanyG** [comment]
Curious as to why this is an enhancement?  These tests are broken in current code.

**Comment by billglover** [comment]
Would be great if these tests could:

* Be executed with `manage.py test`
* Populate whatever data they need to run
* Remove that data once complete

**Comment by BethanyG** [comment]
**NOTE** Model_mommy is no longer maintained.  [**Model Bakery**](https://pypi.org/project/model-bakery/) is the recommended migration.


AFIK, `manage.py test` via `unittest` and `PyTest` takes care of:

* Creating a test DB, 
*  Loading (or creating, depending on the libraries used) data into the test DB, 
*  Running the tests (provided they are prefaced with **test** in their name)

..but weather or not the loaded data is generated on the fly or is static  (**fixtures**) depends on how the tests are written.  Right now, they are super basic and pretty fragile.

**Comment by billglover** [comment]
> "Model Bakery offers you a smart way to create fixtures for testing in Django. With a simple and powerful API you can create many objects with a single line of code."

**Comment by BethanyG** [comment]
Since I do not have strong opinions for using one of these over the other, I'm going to go with [**Factory-Boy**](https://factoryboy.readthedocs.io/en/latest/), both because @chris48s is familiar with it, and because it works for projects beyond Django, and is therefore a good testing tool for potential contributors to learn.   

Open to additional opinions or discussion, but changes beyond this point need to include Chris and any others who are writing tests so that their work isn't  invalidated or broken by a library decision.

**Comment by BethanyG** [comment]
@chris48s  -- we also have [**Faker**](https://faker.readthedocs.io/en/master/) installed, but I don't really like what I am reading about how limited the data it produces is.  Granted, I haven't done _extensive_ reading.  Any recommendations there are very welcome.  😄

**Comment by billglover** [comment]
Thank you. This feels like we have a decision to progress with Factory-Boy. Do we want to keep the issue open until we have updated existing tests?

**Comment by BethanyG** [comment]
@billglover  -- yes, I think that's our current strategy.
