### ISSUE TITLE
[File restructuring] Rename cbv3_django_prototype to `app`

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/backend#50]
## Context
h/t @billglover who pointed out  `cbv3_django_prototype` could probably be renamed to `app`, now that we've decided on this course.

## Acceptance Criteria
We'll need to make sure to rename in the following places
- folder/file structure
- inside the Dockerfile
- other places (??)

**Comment by lpatmo** [comment]
Let's not work on this issue right now, but only after the Dockerfile is merged and after #43 is addressed.

**Comment by billglover** [comment]
Could be completed with #31 and #50.

**Comment by tgrrr** [comment]
@billglover renaming it to app makes sense, except... It would be better to complete issues with their own ticket, rather than with #31 or #50

**Comment by BethanyG** [comment]
Would be great to now take this on along with #30 & #31, since the current file structure with the repeated `cbv3_django_prototype` name appears to have broken the test runner.

**Comment by billglover** [comment]
Removing the `hold` tag on this so this is now available.

**Comment by BethanyG** [comment]
@lpatmo   do we want to take this on with the other re-org tasks in one fell swoop before proceeding with additional application changes?  Might be a good time to hit pause on code changes and bite the bullet, along with making sure deployments, configuration, and testing all work with a revised folder structure.  Still not clear (really) on what magic Cookiecutter is using vs this simply being the way folders are arranged.

**Comment by lpatmo** [comment]
I took a look at this by changing the `cbv3_django_prototype` in both the project folder and app folder to `app`, and then doing a grep for all the appearances of `cbv3_django_prototype` and changing it to `app`. 

It caused a bunch of "cannot import app.users" errors.

![image](https://user-images.githubusercontent.com/4512699/75088249-784e1c00-54ff-11ea-8386-8c6b179806b7.png)

After I did `git checkout .` for the changes and ran `docker-compose down` and `docker-compose up --build`, I still got errors. :P I ended up checking out the `master` branch again (which was fine) and creating a new branch, and cherry-picking the previous file-restructuring commits to that branch for PR #87. 

Anyway, my next steps:

1. Try changing `cbv3_django_prototype` only on the upper level

**Comment by lpatmo** [comment]
Update: tried that (changing `cbv3_django_prototype` to `app` only on the upper level) but got:

![image](https://user-images.githubusercontent.com/4512699/75088348-d9c2ba80-5500-11ea-8311-843cbdfa97cc.png)

and

![image](https://user-images.githubusercontent.com/4512699/75088354-e6471300-5500-11ea-9330-313dbf369894.png)

**Comment by billglover** [comment]
This is closed by #99.
