### ISSUE TITLE
[discussion] re-name this repository

### ISSUE THREAD

**Issue by billglover** [codebuddies/backend#61]
The proposal is that we rename this repository to **backend**.

Why: Now that we have decided to use Django as the back-end for future versions of CodeBuddies, it no longer makes sense to retain the **django-concept** name. Calling this **backend** will make it clearer to contributors what the role of the repository is.

Why now: We have just force pushed a solution to #53 causing disruption to anyone who had forked the repository. Renaming the repository is disruptive and doing so now will ensure we minimise disruption to anyone working with remote or forked copies of the repo.

What if we don't do anything: If we don't make this change, we will either retain the confusing repository name or we will have to perform this disruptive change in the future when it risks being disruptive to more contributors.

**Comment by brylie** [comment]
FWIW, GitHub automatically redirects renamed repositories.

**Comment by billglover** [comment]
Anything I'm missing before going ahead and implementing this one?

I'm proposing this one gets two approvals before implementation.

**Comment by lpatmo** [comment]
Will make the change. Thanks for pushing this forward, @sunu @billglover et. al!

**Comment by lpatmo** [comment]
A few years ago we had to rename a github repo `codebuddiesdotorg` to `codebuddies`, so this won't be the first time. :)

**Comment by lpatmo** [comment]
✔️ Renamed to `frontend` and `backend`
