### ISSUE TITLE
Deploy the master branch to production

### ISSUE THREAD

**Issue by billglover** [codebuddies/backend#65]
We don't yet have a production deployment of the CodeBuddies backend. We should have one.

**Why?**:
Deploying a publicly accessible version of the CodeBuddies backend will allow us to get feedback from the CodeBuddies community.

**Why now?**:
The earlier we get feedback, the easier it is to address. We have functionality that is very close to being ready for user testing. It would be good to have an environment to deploy to in time for release.

**What if we don't implement?**:
User testing will require users to stand up their own environments. This makes it less likely that a user will use features to accomplish real tasks.

## Acceptance

* [x] publicly accessible deployment of the CB backend
* [x] ~publicly accessible deployment of the CB frontend~
* [x] tagged changes to `backend/master` trigger a deployment of the CB backend

*Edit:* Removed frontend from the acceptance criteria as that is being deployed differently.

**Comment by billglover** [comment]
Some initial thoughts:
* Assume Digital Ocean is the target hosting provider
* Separate subdomain: https://api.codebuddies.org/
* Certificate provided by LetsEncrypt
* Application packaged as DockerContainer
* Tagged Docker image pushed to Docker Hub
* Database on same host as application
* Same web server for static content acts as proxy for Django app
* Only tagged changes will be deployed

**Comment by lpatmo** [comment]
- Database hosting on Digitalocean's managed DB hosting: https://www.digitalocean.com/products/managed-databases/

I did not realize "tagged PRs" -> deployment was a thing! Are you talking about this process? https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

**Comment by lpatmo** [comment]
One thought:

What are your thoughts on deploying an https://api.codebuddies.org/ that our React app could make requests to, but with the understanding that all this data is in beta and isn't temporary until we officially launch a beta?

**Comment by billglover** [comment]
> What are your thoughts on deploying an https://api.codebuddies.org/ that our React app could make requests to, but with the understanding that all this data is in beta and isn't temporary until we officially launch a beta?

This should be something we aim for as soon as possible. I'd say data isn't guaranteed until the main CodeBuddies site is switched over to use the new backend.

**Comment by sebbel** [comment]
+1 for getting something out asap. I could help with deployment, like server setup etc.

**Comment by billglover** [comment]
Would love some help on this. An initial step could be to understand what infrastructure we already have available to us. I'm hoping we can run this on an existing Digital Ocean server as the resource requirements should be tiny.

**Comment by lpatmo** [comment]
@billglover I added you, @sebbel, and @BethanyG to the DigitalOcean team. I created a new Postgres instance last night, but didn't get around to a deployment tutorial. 

I am not entirely sure how to deploy this on an existing Digital Ocean server, heh. But actually a new VM should be fine -- we have enough credits from DO's sponsorship to afford it! https://www.digitalocean.com/community/tutorials/how-to-set-up-a-scalable-django-app-with-digitalocean-managed-databases-and-spaces

Would love to pair (https://calendly.com/lindapeng/pairing?month=2020-02) on this, but if the scheduling is tricky happy to record a video of the explorations (with creds hidden of course) to share with everyone later. Feel like we could make the deployment process transparent (minus any sensitive info) to help future developers.

The bits I have no idea how to do/would need to find a tutorial for:
- Application packaged as DockerContainer
- Tagged Docker image pushed to Docker Hub

**Comment by billglover** [comment]
I scheduled a pairing session tomorrow. Maybe we can use that to make a start. My hope is that we can deploy this very similar to the way we run things locally.

I'm most worried about:

* building a production version of the Django application
* running migrations against a live site
* deploying older versions (i.e. roll-back) - do we even want to do this?

**Comment by billglover** [comment]
We took 20 minutes to attempt a production deployment and got so close. DB and app deployed, migrations ran successfully. We didn't manage to expose the API externally but have some things to investigate.

I've created the following page on the wiki where we plan to document this:
https://github.com/codebuddies/backend/wiki/Production-Deployment

**Comment by lpatmo** [comment]
Blog post title: how to deploy your Django app in only 20 minutes using Docker

**Comment by billglover** [comment]
I've added a new action on the associated branch that builds the container image and publishes it to the GitHub package repository instead of Docker Hub. You can see the first version of the container image here: https://github.com/codebuddies/backend/packages/

Next steps are to extend this action to add a deployment step that updates the deployment on a Digital Ocean droplet.

**Comment by billglover** [comment]
Some documentation:
https://github.com/codebuddies/backend/wiki/Production-Deployment

**Comment by BethanyG** [comment]
@billglover  - can this issue be closed as completed??

**Comment by billglover** [comment]
This is definitely stale and can be closed. It was never implemented. The work done may be of interest, but I'm closing the issue.
