### ISSUE TITLE
[API]  Tags is a Required Field for POST-ing a Resource

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#74]
Currently, the model for `Resouces` has `tags = TaggableManager(blank=True)`, and while this will allow a *blank* `tags` field, it will not allow a poster to **omit** the `tags` field from the POST.

This is not desirable, and we will need to consider if we would like to write code to apprehend the incoming POST to check for the missing field and supply it , as opposed to throwing a "this field is required" error...or otherwise research how to make the code more flexible so that the field is not required.

**Comment by lpatmo** [comment]
From a React perspective, I think this is fine! That is, we can be explicit about requiring a `tags` field in the form to submit a resource. The other conclusion is that every endpoint will need a `tags` field supplied (and a tags field in the UI), right?

Are there other scenarios I'm missing?

**Comment by billglover** [comment]
I think we need to remove the requirement for an empty array. Expected behaviour when calling an API is that optional fields do not need to be provided. It would be unusual to require an array but not require it to contain any values.

It could be worked around in react, but any other consumer of the API would also have to work around this issue.

**Comment by BethanyG** [comment]
Color me totally relieved that this is an area where Django/DRF made it _easy_.  Turns out, I needed to supply a **default** value that triggers a blank field save.  [**Here**](https://www.django-rest-framework.org/api-guide/fields/) are the docs I worked from, and here is the code change needed:

```python
class ResourceSerializer(TagSerializer, serializers.ModelSerializer):

    #adding default="" here causes the field to not be required by DRF
    tags = TagsSerializerField(model_field='tags', default='')
    media_type = serializers.SerializerMethodField()
    user = UserSerializer(read_only=True)

     ...

```

Currently working in a branch to try several of the proposed tag changes and fixes, so this will be part of an upcoming PR...but if it's making you crazy, you can patch your code with the above, and that should take care of it.

**Comment by billglover** [comment]
This is an awesome find, nice one!
