### ISSUE TITLE
[access request] grant access to Docker Hub Organisation

### ISSUE THREAD

**Issue by billglover** [codebuddies/backend#75]
Please add me as a member of the codebuddies organisation(s) on Docker Hub.

* https://hub.docker.com/u/codebuddies
* https://hub.docker.com/u/codebuddiesdotorg

I require access to be able to push versions of the codebuddies image as part of implementing #65.

**Comment by lpatmo** [comment]
Thanks for this reminder. Sent you an invite! :)

**Comment by billglover** [comment]
Thanks! I now have access to:
* https://hub.docker.com/u/codebuddiesdocker/

Do you know who controls the following:
* https://hub.docker.com/u/codebuddies <-- I'm particularly interested in this one
* https://hub.docker.com/u/codebuddiesdotorg

**Comment by lpatmo** [comment]
Ahhh I can't figure out the login for https://hub.docker.com/u/codebuddies, sorry :( Looks like it's an organization account now (saw that message when I was resetting my password), so I'm not sure if I have a separate private email that has access to it. Am double checking. 

@nalbina Do you remember creating a docker account for codebuddies in 2017?

https://hub.docker.com/u/codebuddiesdotorg I own btw -- and you have access to it now, right?

**Comment by billglover** [comment]
Yup all good thanks, going to close the issue. The reason the u/codebuddies account was of interest is that it allows you to use shortened names if the image name is the same as the organisation name.
