### ISSUE TITLE
[API] Create Projects Django App and associated apps.py Files

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#81]
Create a Django app `osprojects` for the new  **Osprojects** api endpoint, and a `apps.py` file to go with it.

See [**Django startapp**](https://docs.djangoproject.com/en/3.0/ref/django-admin/#startapp) for some details on how to do this either via the `manage.py` app, or manually.

**Comment by billglover** [comment]
Are we using branch [issue-79-add-projects-endpoint](https://github.com/codebuddies/backend/tree/issue-79-add-projects-endpoint) for this work? I would urge caution as this now differs significantly from `master`. Please let @codebuddies/backend know if help is needed.

**Comment by lpatmo** [comment]
Thanks for the reminder! I've rebased the `issue-79-add-projects-endpoint` branch from master.

cc @bkbuilt -- please pull and `git rebase master` also if you've started working in a new branch for this or another issue :)

**Comment by BethanyG** [comment]
@bkbuilt  - are you still working on this and the associated issues?

**Comment by BethanyG** [comment]
Closing this as no longer relevant to current development.

**Comment by lpatmo** [comment]
Re-assigning this to @watchtheblur. 

```
docker-compose run --rm app python django-admin startapp osprojects
```

**Comment by BethanyG** [comment]
@lpatmo  -- good catch with the docker compose command.  All of these related issues were logged without considering `docker compose` -- so I am really glad you added that in!
