### ISSUE TITLE
[API]  Create Views and Queries for Projects Endpoint

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#82]
Create  views for the new Projects API Endpoint.  Some of these items may not need custom code, but are listed here as a reminder of what's needed:

[ ]  Create **list** and **detail** views for the endpoint.  See the [**DRF ModelViewSet**](https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset), [**DRF Generic Views**](https://www.django-rest-framework.org/api-guide/generic-views/#generic-views) and [**DRF CreateModelMixin**](https://www.django-rest-framework.org/api-guide/generic-views/#createmodelmixin) for background and places to start.

[ ]  Add an `ISAuthenticated` permissions class to require a login for the endpoint.  See [**Permissions in DRF**](https://www.django-rest-framework.org/api-guide/permissions/)

[ ]  Add search or filter backends as needed.  See [**DB queries in Django**](https://docs.djangoproject.com/en/3.0/topics/db/queries/), [**DRF Filter Backends**](https://www.django-rest-framework.org/api-guide/filtering/#setting-filter-backends), [**Filtering in DRF**](https://www.django-rest-framework.org/api-guide/filtering/), and [**DRF SearchFilter**](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) for some background to start.

[ ]  Add `search_fields` for endpoint

[ ]   Add PATCH function to update records already in the DB

[ ]   Add `perform create` function as needed for specialized user lookup or other (e.g. many-to-many) relations.

[ ]  Add/define `queryset` for the list view of `projects`

[ ]  Add links to associated serializers

See https://github.com/codebuddies/backend/blob/master/cbv3_django_prototype/cbv3_django_prototype/resources/views.py as one (but not canonical) example.

________

**WARNING:**  There may or may not be more complicated logic here around how we pull the **contributors** list.  Current working model potentially has a **manytomany** filed relating projects to contributors.

**Comment by BethanyG** [comment]
Closing as no longer relevant to current development.

**Comment by lpatmo** [comment]
Probably looking at this with @tgrrr and @bengineerdavis tomorrow (and others welcome) in this hangout: https://codebuddies.org/hangout/nAadjwkpEsF9gsTGM

**Comment by tgrrr** [comment]
> Closing as no longer relevant to current development.

Is this issue still no longer relevant @BethanyG ?

**Comment by BethanyG** [comment]
@tgrrr  Please read the comment from @lpatmo  above, as this issue was reopened by her after I had closed it.  Please also refer to the discussion on #157 should you need more context around why this endpoint was closed and is now being reopened step by step.  Please also see issue #79 as the tracking issue for this endpoint.  Thanks!

**Comment by tgrrr** [comment]
I've created a branch to keep the work on this issue together here: [issue-82-views-queries-projects-endpoint](https://github.com/codebuddies/backend/tree/issue-82-views-queries-projects-endpoint)

**Comment by BethanyG** [comment]
@lpatmo   are you still working on this?  Should we remove the "stale" tag?

**Comment by lpatmo** [comment]
Thanks for reminding me! @bengineerdavis actually has the latest on this in a branch, if I remember correctly. I have a pretty good idea of how to make changes in the API now after finishing the tutorial and helping Ben and J with this, but I'm not actively working on this ticket anymore -- I will un-assign myself.

**Comment by BethanyG** [comment]
still open.
