### ISSUE TITLE
[API]  Register Projects Endpoint with Admin Interface and Create Admin Views

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#84]
We will want the ability to review/administer the **Projects** endpoint through the Django Admin interface, and so will want to register our `projects` app with the Django admin and provide any custom admin views we think we'll need.

See [**The Django Admin Site**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#overview), [**Admin Actions**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/actions/), and [**Customizing the Admin**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#customizing-the-adminsite-class) for more details on how to start.

See [**Resources : admin.py**](https://github.com/codebuddies/backend/blob/master/cbv3_django_prototype/cbv3_django_prototype/resources/admin.py) for an example of how the `resources` endpoint customized the Admin to display tags appropriately. 

Since `projects` will also include a potential **manytomany** relation with **users**, there may need to be additional customization around that for the Admin interface.

**Comment by BethanyG** [comment]
As of **PR** https://github.com/codebuddies/backend/pull/96, tags serialization is handled by an app, **`tagging`**.  Below is an example from **`resources/admin.py`** on how **tagging** is used:

```python
class ResourceAdmin(admin.ModelAdmin):

    list_display = ['tag_list']

    def get_queryset(self, request):
        return super().get_queryset(request).prefetch_related('tags')

    def tag_list(self, obj):
        return u", ".join(o.name for o in obj.tags.all())

admin.site.register(Resource)
```

**Comment by BethanyG** [comment]
Closing as no longer relevant to current development.

**Comment by watchtheblur** [comment]
working on it now

**Comment by watchtheblur** [comment]
Django admin errors out with "Internal Server Error" when I have the following code in admin.py
```python
class OSProjectAdmin(admin.ModelAdmin):

    list_display = ['tag_list']

    def get_queryset(self, request):
        return super().get_queryset(request).prefetch_related('tags')

    def tag_list(self, obj):
        return u", ".join(o.name for o in obj.tags.all())
```

**Comment by BethanyG** [comment]
@watchtheblur - I think you're missing a couple of pieces of info in the osprojects/admin.py file.

First, (and I always forget this!) you need to import your model at the top of the file so that Django knows what DB tables are going to be administered through the admin interface.  For `osprojects`, the two imports should be:

```python
from django.contrib import admin
from .models import OSProjects
```

Then, at the bottom of your class you should add the line `admin.site.register(OSProjects)` to make a formal call to register the project.  

So the whole file should look like this:

```python
from django.contrib import admin
from .models import OSProjects


# Register your models here.
class OSProjectAdmin(admin.ModelAdmin):

    list_display = ['tag_list']

    def get_queryset(self, request):
        return super().get_queryset(request).prefetch_related('tags')

    def tag_list(self, obj):
        return u", ".join(o.name for o in obj.tags.all())


admin.site.register(OSProjects)
```

When I added those two pieces of info onto the branch I tested for your model changes, my server started up, and I was able to see OSProjects in the admin interface.  You can also take a look at `resources/admin.py` for another example how the resource endpoint did this.

Let me know if you continue to have issues, and we can maybe schedule a time to interactively debug.  😄

**Comment by watchtheblur** [comment]
@BethanyG Thanks for looking into this!  I'd love some time to interactively debug this!  How should I coordinate with you to find a good time? (Slack/github?)

We took cue from resources/admin.py as you recommended. Here's my current, full osprojects/admin.py:

```py3
from django.contrib import admin
from .models import OSProjects

# Register your models here.


# class OSProjectAdmin(admin.ModelAdmin):

#     list_display = ['tag_list']

#     def get_queryset(self, request):
#         return super().get_queryset(request).prefetch_related('tags')

#     def tag_list(self, obj):
#         return u", ".join(o.name for o in obj.tags.all())

admin.site.register(OSProjects)
```

We commented out the code that seem to break the admin interface.

**Comment by BethanyG** [comment]
@watchtheblur  Ooof.  So even with the changes, you still have the error?  That is indeed strange.  Yes - let's set up a time to interactively debug this.  I am as interested in why this **does** work for me as I am in why it **doesn't** for you!  _Smells like a mis-applied migration or weird data state...._ 🤔 .  Pinging me on Slack is the easiest for scheduling quickly.  I am in PDT (same timezone as @lpatmo), and usually have time afternoons/evening.  However, if you are in a African/Asian/Euro/Aussie timezone, I can be flexible with warning.  😄

**Comment by BethanyG** [comment]
Just to document the steps I used to (**not** --  _sadly_) reproduce this error:

I am on a Mac running MacOS Mojave.  
I am using Docker Desktop for Mac Community v2.3.0.4(46911)
The Docker engine is at v19.03..12 and Docker-Compose is at v1.26.2

1.  I removed all containers for the project via `docker-compose rm` (_so I could force a rebuild of all containers and components_)
2. I removed the entire db/data volume for the project  via `docker volume rm  backend_db_data` (_so that I was starting with no DB, and forcing a rebuild of that as well_)
3. Made sure I refreshed my fork from my computer with all of the latest updates to main via `git fetch upstream` & and `git rebase upstream/main`
4. Made a branch locally to test these changes via `git checkout -b test-admin-changes`
5. Applied new `admin.py` file change to the `osprojects` folder (_the DB change was already part of the changes I pulled from upstream/main_)
6. Created a superuser for the django admin via `docker-compose run --rm app python ./manage.py createsuperuser`
7.  Built & started the project via `docker-compose up --build`
8.  Monitored the logs
9.  Brought up the application at `localhost:8000`
10. Logged into the admin interface via `localhost:8000/admin`
11.  Added three new OSProjects with tags
12.  Edited those projects
13.  Edited some tags

I did not see any errors.

If the steps above don't fix this, we've go a serious problem.  @lpatmo  -- are you also seeing this issue?  If so, can you paste in a stack trace or give me some steps to reproduce?  This may be connected to seed data in the DB or a configuration problem.  Thanks!

**Comment by lpatmo** [comment]
Thanks for testing it out! Recreating now...

1) git pulled the latest from `main`
2) Ran `docker-compose run --rm app python ./manage.py migrate` since I was seeing the following:
![image](https://user-images.githubusercontent.com/4512699/92417936-caf8c980-f119-11ea-9271-d0329de625ae.png)

3) Created a new superuser

4) Put the following into `osprojects/admin.py`: 

```
from django.contrib import admin
from .models import OSProjects

# Register your models here.


class OSProjectAdmin(admin.ModelAdmin):

    list_display = ['tag_list']

    def get_queryset(self, request):
        return super().get_queryset(request).prefetch_related('tags')

    def tag_list(self, obj):
        return u", ".join(o.name for o in obj.tags.all())


admin.site.register(OSProjects)

```

Was able to create new projects with tags.

No errors on OSX.

@watchtheblur Can you share a screenshot or a screenrecording of the "Internal Server Error" we were seeing? I don't remember that there were stack traces (it was a blank screen with the words "Internal Server Error" IIRC, that would only appear with the tags code in there). We can also try Twitch streaming this if it's easier to record that way.

**Comment by BethanyG** [comment]
@lpatmo  @watchtheblur   Is this still being worked on, or does it need to be closed?

**Comment by lpatmo** [comment]
Looks like `osprojects/admin.py` file got merged in at one point, but in any case we can close this particular issue! :)
