### ISSUE TITLE
[API]  Create `Projects` Endpoint URLs and Mapping

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#85]
We'll need to create url.py entries for our new `Projects`  API - both in the main **`urls.py`** file, and in the  **projects/`urls.py`** file

[ ]  Create/add `urlpatterns` as necessary to **projects/`urls.py`**.  Include **`projects/`**, **`router.urls`**, and **rest_framework_urls** as needed.  See [**url dispatcher**](https://docs.djangoproject.com/en/3.0/topics/http/urls/) for detailed background, and [**Including other URLconfs**](https://docs.djangoproject.com/en/3.0/topics/http/urls/#including-other-urlconfs) for a quicker example. 

[ ]  Register the appropriate DRF _**router**_ for these urls see [**DRF Routers**](https://www.django-rest-framework.org/api-guide/routers/)  for details.

[ ]  Create/add `urlpatterns` as necessary to **config/`urls.py`**, to include `projects..urls`

See [**resources : `urls.py`**](https://github.com/codebuddies/backend/blob/master/cbv3_django_prototype/cbv3_django_prototype/resources/urls.py) as an implementation example.

**Comment by billglover** [comment]
Are we using branch [issue-79-add-projects-endpoint](https://github.com/codebuddies/backend/tree/issue-79-add-projects-endpoint) for this work? I would urge caution as this now differs significantly from `master`. Please let @codebuddies/backend know if help is needed.

**Comment by BethanyG** [comment]
Closing as no longer relevant to the current development.
