### ISSUE TITLE
[API]  Store Tag Serializer Code as a **tagging** app for Use Across Endpoints

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#86]
Currently, we are assuming most endpoints will have **Tags** and we are also using `taggit` for tag management.  

Our current `taggit` model required custom serializer code to make tags for `resources` display appropriately, and the expectation is that this same code (or some improved or different version) will be required for any endpoint that is using `taggit` or tags.

We should therefore move the **TagSerializer** and **TagsSerializerField** code out of `resources`, and into a common ~~utility file or~~ location for ease of import and use to other endpoints (and to better discuss and maintain it as a module).

~~Propose it be moved to the **`utils.py`** file, where we also have the jwt response handler code...or another common or core place.~~

Propose a **tagging** app for storing tagging related serializers, views, and functions.

**Comment by billglover** [comment]
Based on conversation on Slack it looks like a decision was made to move this to its own `app` (also known as a `module`).

**Comment by BethanyG** [comment]
Yes.  Following the recommendation of Kenneth.  Changed the issue title/description accordingly.  This will be part of the PR that includes #71 &  #74.
