### ISSUE TITLE
Proposal to move set-up instructions to the Wiki

### ISSUE THREAD

**Issue by billglover** [codebuddies/backend#88]
Anyone visiting the project repo risks being overwhelmed with technical set-up instructions, screenshots, choices and links to various issues. I've raised this issue to propose a different structure. I'd like to lean on the work done to standardise [community health files](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file). I propose, but not necessarily in this order:

* Overview of CodeBuddies
* Role of the Backend
* Links to Clients / Front End
* Tech used
* Link to SUPPORT.md
* Ways to get involved
* Link to CONTRIBUTING.md
* Link to CODE_OF_CONDUCT.md

**Acceptance Criteria:**
* [ ] agreement on the structure of the README
* [ ] new version of the README following the agreed structure
* [ ] placeholders with structure for community health files

**Comment by lpatmo** [comment]
I started a rough rough draft of what the new README.md could look like here:

https://docs.google.com/document/d/1F7EJWK8HTTUGpw7g35I5Hs9nktaSLtd-BkCTWbVy07Y/edit#

**Comment by billglover** [comment]
This looks good. I added a couple of comments around the tech used in deployment and hosting but I think this is ready to go.

Steps to close:
* [ ] create a branch and submit changes to README.md
* [ ] raise PR and request review from @codebuddies/backend 
* [ ] respond to review comments (if any)
* [ ] merge

**Comment by bengineerdavis** [comment]
@nuageklow @billglover I would also like to join an assignee to this issue, if that is available. Karen, let me know if you want to collborate or you still have an interest in taking this on--I'm happy to follow your lead!

**Comment by nuageklow** [comment]
Currently importing Linda's content to a community_health_file.md. https://github.com/nuageklow/backend/blob/master/community_health_file.md. Feel free to give me feedback on this :)

**Comment by lpatmo** [comment]
@nuageklow That looks like a great start! When you make the PR, the contents of that should replace README.md :) (in case that wasn't clear). Thank you!

(And then @bengineerdavis is working on moving the setup instructions currently in our README into a new CONTRIBUTING.MD file.)

**Comment by nuageklow** [comment]
im done drafting the md file :) could anyone take a look to see if there is anything that needs to be changed? 
or should i just submit a PR directly?

**Comment by billglover** [comment]
Thank you @nuageklow. Please submit the PR. When you do it provides a way for people to leave feedback.

**Comment by bengineerdavis** [comment]
I won't be able to contribute to this issue for the time being, feel free to un-assign me for now, and I will follow up when I have more time to work on this.

**Comment by billglover** [comment]
@bengineerdavis no problem at all. I've removed the assignment.

**Comment by nuageklow** [comment]
hey everyone. sorry for disappearing for so long. was browsing the issue list and realized this was never done :/ not sure if anyone else is helping out on it. if not i'll catch up on slack first and will start working on it.

**Comment by lpatmo** [comment]
Sorry I missed your message here, @nuageklow. Thanks for helping clear up Windows instructions last weekend! 

It looks like all our contributing.md instructions are now cross-posted between the README.md and CONTRIBUTING.md, and tbh I don't mind being able to search for the docker commands in the README.md itself. But as Bill pointed out here originally, all the detailed information may be overwhelming. Do we still want the following structure? 

Overview of CodeBuddies
Role of the Backend
Links to Clients / Front End
Tech used
Link to SUPPORT.md
Ways to get involved
Link to CONTRIBUTING.md
Link to CODE_OF_CONDUCT.md

**Comment by billglover** [comment]
It might be an idea to bring the Code of Conduct link nearer to the top, but other than that the structure looks good to me.

**Comment by BethanyG** [comment]
@lpatmo @nuageklow  -- can we close this, or is more work needed?

**Comment by lpatmo** [comment]
@nuageklow told me she was working on this a while ago, but at this point I think would be easier if I quickly wrapped this up since the long thread makes following along a little confusing! 

TODO: 
- [ ] Update README to follow the format in https://docs.google.com/document/d/1F7EJWK8HTTUGpw7g35I5Hs9nktaSLtd-BkCTWbVy07Y/edit
- [ ] Move all contributing instructions over to CONTRIBUTING.md

**Comment by nuageklow** [comment]
i apologize for dragging this very long! @lpatmo   maybe i can pass the files i've already done to you soon hopefully that can save you sometime.

**Comment by lpatmo** [comment]
No worries @nuageklow! This was not the easiest PR since there was a lot of content to navigate :P I opened up a PR at https://github.com/codebuddies/backend/pull/195 over the weekend, if you'd like to do a quick review/approve it. Thanks!

**Comment by lpatmo** [comment]
Issue closed by https://github.com/codebuddies/backend/pull/195 :)
