### ISSUE TITLE
Creating and populating initial Contributing.md 

### ISSUE THREAD

**Issue by bengineerdavis** [codebuddies/backend#90]
After speaking with Linda, Bethany, and many others in the community, we are overdue for a more formal and detailed structure to our documentation of the backend, which I'll be adding in myself.

My checklist:

- [ ] Create Contributing.md

- [ ] Migrate all contributor-related content from README to Contributing.md

- [ ] Add my proposed changes to the Postman setup

- [ ] Merge into this issue? https://github.com/codebuddies/backend/issues/88

- [ ] Also Merge other issue into this issue: https://github.com/codebuddies/backend/issues/70

[Issue 70](https://github.com/codebuddies/backend/issues/70) checklist: 
Links: [here](https://github.com/codebuddies/backend/issues/70#issuecomment-589619138) and [here](https://github.com/codebuddies/backend/issues/70#issuecomment-589514260)

- [ ] Document guidance for PR reviewers to check that model changes are accompanied by associated migrations. Suggested location [on wiki](https://github.com/codebuddies/backend/wiki/Contribution-Instructions#reviewing-prs)
"**Note:** This is a working document. When we have settled on a reasonable structure to our Contributing Guidelines, the contents of this document should be moved to CONTRIBUTING.md in line with [GitHub guidance](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)." (from Wiki)

- [ ] Document guidance for contributors to ensure they are running makemigrations at an appropriate point. Suggested location on wiki.

- [ ] Update the README (setup step 4) to include the --build flag to ensure dependencies are updated if necessary.

**Comment by bengineerdavis** [comment]
Hi all, because of all the craziness and other foreseen circumstances, this should be assigned to someone else. I will, when time allows, come back to this or contribute through another PR here.

**Comment by lpatmo** [comment]
No worries at all and thank you, @bengineerdavis! I will put out the call if someone else is interested in taking this; otherwise I will tackle it. 

PS I think you should also have the ability to un-assign yourself (for future reference). :)

**Comment by nuageklow** [comment]
Hi I can help with the initiation of contributing.md. Will follow up with you guys if i run into any issues :)

**Comment by lpatmo** [comment]
Thank you so much, @nuageklow!

**Comment by nuageklow** [comment]
Currently working contributing.md and want to double check on the current README.md section Step no. 5 creating superuser. Is it required for every CBV3 contributor to create their own superuser account? From my understanding superuser account is not required to run manage.py for django.

**Comment by nuageklow** [comment]
oh no sorry for keep missing stuff :( I'll fix it soon!

**Comment by BethanyG** [comment]
@nuageklow  -- are you still working on this, or can we close it for now?

**Comment by nuageklow** [comment]
@BethanyG it should be done for now sorry. will close the issue now.
