### ISSUE TITLE
[Tooling] Looking at & Managing the Project Dependency Tree

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/backend#97]
### Thoughts | Concerns | Recommendations on Dependency Tree Management  

**Ideally, any system proposed should do the following with minimal tooling.  
It also needs to work with our docker dev setup with minimal configuration.**

1.  Identify dependencies that have new versions available
2.  Identify unused dependencies and remove them
3.  Identify dependency conflicts at the time they are introduced  

___

#### Background
Per bug #78 - we're at a point where we need to explore and discuss tools for looking at and managing our project dependency tree.  From @billglover [comments](https://github.com/codebuddies/backend/issues/78#issuecomment-591292566) in the issue:

> I'd like to be able to:
> 
> * identify dependencies that have new versions available
> * identify unused dependencies and remove them
> * identify dependency conflicts at the time they are introduced

_______
And @BethanyG added the following comments:

> I haven't tested out all of these...it's a process. But I did want to note what I dug up here so you could explore as well. This [**Blog Post by Hynek Schlawack**](https://hynek.me/articles/python-app-deps-2018/) was a place I started to get some lay of the land. It's highly opinionated, of course. [**The post by Nick Timkovic**](https://medium.com/telnyx-engineering/rip-pipenv-tried-too-hard-do-what-you-need-with-pip-tools-d500edc161d4) - recommended by @chris48 in Slack was also informative.
> 
> 1. [**`pip-tools`**](https://github.com/jazzband/pip-tools) (_as recommended in the above blog post_).  Does attempt to check off points one and three, but doesn't clean the tree - nor let you **see** the tree, for that matter.
> 2. [**`pipdeptree`**](https://github.com/naiquevin/pipdeptree)  current build is broken, but this still looks intriguing.  At least we could run it and see our tree.  Some [notes](https://necromuralist.github.io/posts/pip-tools-and-pipdeptree/) I found on it.
> 3. [**`pipreqs`**](https://pypi.org/project/pipreqs/) designed to generate `requirements.txt` files based on **imports** in a project, rather than installed packages.  Might be worth a shot to diff our `requirements.txt` files against this and see which is smaller...
> 4. [**`pip-autoremove`**](https://pypi.org/project/pip-autoremove/)  removes a package and any of its unused dependancies.
> 5. Wrong direction here..but [**`pip_check_reqs`**](https://pypi.org/project/pip_check_reqs/) will check for modules that you **should** include at the top level that were only included because of a dependancy.
> 6. [**poetry**](https://python-poetry.org/docs/cli/) as a tool to make it "easier" to manage all this.  But yes - another tool and another dependency itself.
> 7. [**hatch**](https://github.com/ofek/hatch) but really?  They are trying to make a different version of Cookiecutter with venvs so probably not wanted here.

**Comment by brylie** [comment]
Poetry is nice.
